# Generated by Django 6.0.3 on 2026-04-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_emailtemplate_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntarget',
            name='business_unit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='manager',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
