# Generated by Django 6.0.3 on 2026-04-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_course_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=0,
                help_text='0 = unlimited attempts. Set to 1 to allow only one attempt, 2 for two, etc. The platform-level "Allow Quiz Retake" setting is also checked — if retakes are disabled there, this field is ignored.',
            ),
        ),
    ]
