export const users = [
    {
        id: 1,
        name: 'Alice Smith',
        email: 'asmith@company.com',
        department: 'Human Resources',
        campaign: 'Q1 Urgent Update',
        emailStatus: 'Sent',
        clicked: 'Yes',
        training: 'In Progress',
        score: '45%',
    },
    {
        id: 2,
        name: 'Bob Johnson',
        email: 'bjohnson@company.com',
        department: 'Engineering',
        campaign: 'Fake Invoice',
        emailStatus: 'Sent',
        clicked: 'No',
        training: 'Completed',
        score: '100%',
    },
    {
        id: 3,
        name: 'Charlie Davis',
        email: 'cdavis@company.com',
        department: 'Sales',
        campaign: 'Q1 Urgent Update',
        emailStatus: 'Failed',
        clicked: 'No',
        training: 'Not Started',
        score: '0%',
    },
    {
        id: 4,
        name: 'Diana Prince',
        email: 'dprince@company.com',
        department: 'IT Support',
        campaign: 'Q3 Password Reset',
        emailStatus: 'Sent',
        clicked: 'Yes',
        training: 'Completed',
        score: '85%',
    },
    {
        id: 5,
        name: 'Evan Wright',
        email: 'ewright@company.com',
        department: 'Marketing',
        campaign: 'Fake Invoice',
        emailStatus: 'Failed',
        clicked: 'No',
        training: 'Not Started',
        score: 'N/A',
    },
]
