# Generated by Django 6.0.3 on 2026-04-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_alter_platformsettings_lms_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='_reminder_smtp_password',
            field=models.TextField(blank=True, db_column='reminder_smtp_password'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='manager_notify_enabled',
            field=models.BooleanField(default=False, help_text='Notify the manager (if set on target) when their employee clicks the phishing link.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_days',
            field=models.PositiveIntegerField(default=3, help_text='Days after clicking the phishing link before a follow-up reminder is sent.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic follow-up email to employees who clicked but have not completed training.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_from_name',
            field=models.CharField(blank=True, default='Security Awareness Team', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_smtp_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional logo shown on the landing page. Leave blank to hide.', null=True, upload_to='platform/'),
        ),
    ]
