# Generated by Django 6.0.3 on 2026-03-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "admin"), ("hr", "hr")],
                default="admin",
                help_text="Admin = full access. HR = view-only access.",
                max_length=20,
            ),
        ),
    ]
